# Generated by Django 4.0.3 on 2022-04-04 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=3)),
                ('coordinates', models.TextField()),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                            to='chess.pieces', verbose_name='Piece')),
            ],
        ),
    ]
